add icontains to data_attrs operators
maykinmedia/objects-api pull request #239
Opened 2021-09-06 16:09 UTC by annashamray

fixes #235

2021-09-07 13:36 UTC, annashamray commented
this implementations is not what was needed

2021-09-20 09:11 UTC, joeribekker requested changes
Looks good but please change the textual description.

2021-09-20 09:11 UTC, joeribekker commented on src/objects/api/constants.py
> +        "icontains", _("case-insensitive containment, can be used for strings.")
```suggestion
        "icontains", _("case-insensitive partial matches on string values.")
```

2021-09-20 13:52 UTC, joeribekker approved these changes

2021-09-20 13:53 UTC, merged