[WIP] Feature/OIDC integration
maykinmedia/objects-api pull request #247
Opened 2021-09-21 11:56 UTC by stevenbal

2021-09-29 12:53 UTC, annashamray requested changes
Nice! But I think it's better to create staff users with no permissions from the beginning. 

When user tries to log in with OIDC they receive this message:
"You are authenticated as <user id>, but are not authorized to access this page. Would you like to login to a different account? "
And the user can't check if they can actually log in, since we don't have UI except for the admin page. 

Allowing them to enter the empty admin is more user-friendly and at least shows them that their login works 

But perhaps @joeribekker has another option on this.

2021-09-29 12:55 UTC, stevenbal commented
> And the user can't check if they can actually log in, since we don't have UI except for the admin page.

If you check the option `make_users_staff` in the OIDC config in the admin, this should be solved I think

2021-10-04 09:10 UTC, annashamray approved these changes

2021-10-04 13:48 UTC, annashamray commented
Discussed with Joeri. It's fine for now, we can tweak config later

2021-10-04 13:48 UTC, merged