Display UUID and version of any object type in the admin interface
maykinmedia/objects-api pull request #332
Opened 2023-05-19 09:36 UTC by ErhanCitil

2023-05-19 10:23 UTC, joeribekker commented
Make sure your PR description states: `Fixes #315` to link the issue properly.

2023-05-24 12:21 UTC, alextreme commented
@ErhanCitil sync your PR-branches with master to trigger CI

2023-06-01 12:52 UTC, alextreme commented
Aanpak klopt volgens mij niet helemaal. Er dienen geen ObjectRecord relaties te worden toegevoegd.

In plaats daarvan voeg een veld '_version' toe aan de (gecachede) ObjectType. In de clean methode van de ObjectType dient naast '_name' ook in '_version' de versie van het objecttype opgeslagen te worden.

2023-06-01 12:52 UTC, alextreme requested changes
Zie comment

2023-06-05 16:41 UTC, alextreme commented
@ErhanCitil  yubikey lijkt me hier niet in te horen. Ook graag je objectrecord migraties weghalen.

2023-06-06 17:32 UTC, alextreme commented
@ErhanCitil graag je objectrecord migraties weghalen.

2023-06-12 13:18 UTC, alextreme approved these changes
PR is messy due to the requirements upgrade and blacking of migrations, but the addition of _version seems correct.

@annashamray feel free to do a double-check, if this is not (yet) okay please discuss this with Erhan at the office

2023-06-12 18:28 UTC, joeribekker requested changes
3 meta puntjes:

1. Kunnen we black pinnen in deze PR om hem zonder veel black wijzigingen akkoord te krijgen?
2. Deze hele Pr graag in 2 commits: Black pinnen en 315 issue
3. Nieuwe PR met Black update, pinnen op nieuwe versie en black uitgevoerd op alle bestanden.

2023-06-19 15:48 UTC, joeribekker commented
Please rebase so only the relevant changes are shown.

2024-07-05 09:01 UTC, closed without merging

2024-07-05 09:01 UTC, annashamray commented
implemented in https://github.com/maykinmedia/objects-api/pull/393