🔥 [#336] Removed Hijack
maykinmedia/objects-api pull request #343
Opened 2023-06-23 10:27 UTC by ErhanCitil

2023-06-27 15:25 UTC, ErhanCitil commented
@alextreme deze kan ook nagekeken worden

2023-06-27 15:31 UTC, alextreme commented on src/objects/accounts/admin.py
> +class UserAdmin(UserAdmin):
dit kan dan weg volgens mij

2023-06-27 15:34 UTC, ErhanCitil commented on src/objects/accounts/admin.py
> +class UserAdmin(UserAdmin):
> dit kan dan weg volgens mij

Ik kan de `@admin.register(User)` niet gebruiken zonder de UserAdmin class

2023-06-29 11:50 UTC, alextreme approved these changes
Fine by me, but I suspect that @annashamray would like to see the hijack-removal and the blacking of the migrations in two separate commits

2023-07-14 15:28 UTC, annashamray requested changes
@alextreme I think like this PR and https://github.com/maykinmedia/objects-api/pull/341 contradict each other. In PR #341 hijack is even updated 

I think one of them should be closed

2023-07-14 15:28 UTC, annashamray commented on requirements/base.in
> +markdown==3.4.3
Please remove pinned version from base.in, we pin versions in base.txt
And why is this package needed?

2024-01-18 15:32 UTC, closed without merging