:heavy_plus_sign: Add django-log-outgoing-requests
maykinmedia/objects-api pull request #363
Opened 2024-02-23 09:33 UTC by stevenbal

2024-03-05 13:42 UTC, annashamray requested changes
1. Let's have a global var LOG_REQUESTS which switches off and on the logging. You can take a look at the config of open zaak or open forms 
2. Let's turn off saving to the DB by default: 
```
LOG_OUTGOING_REQUESTS_DB_SAVE = config("LOG_OUTGOING_REQUESTS_DB_SAVE", default=False)
```

2024-04-17 14:53 UTC, annashamray commented on src/objects/conf/base.py
> +LOG_OUTGOING_REQUESTS_DB_SAVE = config("LOG_OUTGOING_REQUESTS_DB_SAVE", default=True)
Please add new env vars to the docs

2024-04-22 15:30 UTC, annashamray reviewed
Looks good. 
Could you just rebase and document new env vars? 

Btw is it planned to add django-log-outgoing-requests to open-api-framework?

2024-04-23 07:24 UTC, stevenbal commented
@annashamray there is an issue for it https://github.com/maykinmedia/open-api-framework/issues/14 (and also for setup_configuration https://github.com/maykinmedia/open-api-framework/issues/15)

2024-04-23 09:49 UTC, Coperh commented on src/objects/conf/base.py
> +LOG_OUTGOING_REQUESTS_DB_SAVE = config("LOG_OUTGOING_REQUESTS_DB_SAVE", default=True)
Added to `docs/installation/config.rst`

2024-04-23 12:38 UTC, annashamray approved these changes

2024-04-23 13:21 UTC, merged