bump zgw-consumers to 0.35.1, commonground-api-common to 2.0.1, OAF to 0.9.0
maykinmedia/objects-api pull request #478
Opened 2024-11-25 17:01 UTC by annashamray

fixes https://github.com/maykinmedia/open-api-framework/issues/66

2024-11-27 11:43 UTC, SonnyBA requested changes
The recent changes in the client behavior should be updated in the tests.

2024-11-29 10:35 UTC, stevenbal commented on requirements/base.in
> +git+https://github.com/maykinmedia/commonground-api-common.git@issue/44-migration-error
For now I think this can be removed and you can bump it by running `bin/compile_dependencies.sh -P commonground-api-common==2.1.0`

2024-11-29 10:36 UTC, stevenbal approved these changes
just the comment about the dependency, looks good otherwise

2024-11-29 15:06 UTC, annashamray commented on src/objects/tests/v2/test_notifications_kanaal.py
> +        client.get.return_value = []
I've replaced `patch` with `requests_mock.Mocker` for tests, now it should be correct

2024-11-29 15:06 UTC, annashamray commented on src/objects/tests/v2/test_notifications_kanaal.py
> +        client.get.return_value = []
changed

2024-11-29 15:11 UTC, SonnyBA approved these changes

2024-11-29 15:11 UTC, SonnyBA commented on src/objects/tests/v2/test_notifications_kanaal.py
> +        m.get(f"{NOTIFICATIONS_API_ROOT}kanaal", json=[])
Nice :+1: , not having to know the exact patch location anymore this way.

2024-11-29 15:13 UTC, merged